fix(oci): handling of complex image indexes
aquasecurity/fanal pull request #262
Opened 2021-09-08 06:24 UTC by afdesk

Add a handling of image indexes that contain links to another image manifests.

Fixes [aquasecurity/trivy#1080](https://github.com/aquasecurity/trivy/issues/1080)

2021-09-08 07:58 UTC, knqyf263 requested changes
Great! Thanks! You may forget applying `go fmt` though.

2021-09-14 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/fanal?pullRequest=262) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/fanal?pullRequest=262) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/fanal?pullRequest=262) it.</sub>

2021-09-15 12:50 UTC, afdesk commented
@knqyf263 this PR isn't final, because there isn't a way to select one of inner images

2021-09-30 12:36 UTC, knqyf263 approved these changes

2021-09-30 12:37 UTC, knqyf263 commented
It is enough to take the first image for now.

2021-09-30 12:37 UTC, merged