fix(analyzer): improve performance
aquasecurity/fanal pull request #314
Opened 2021-10-23 10:32 UTC by masahiro331

## Fix the following issue  
https://github.com/aquasecurity/trivy/issues/1295  
https://github.com/aquasecurity/trivy/issues/1284

## Description 

This pull request modifies the walker implementation to improve the amount of memory with some analyzers.

**For Filesystem  command case**

If the file size is large
1. Run os.Open for each execution
2. Also return the clean function and delete the file after everything is done

If the file size is small, read the file only once

**For Image command case**

When the file size is large
1. Get the file from tar and write it to a local file only once
2. Cache the temp file name
3. Open for each execution. 
4. Delete the file after everything is done

If the file size is small, read the file only once

2021-11-29 05:56 UTC, knqyf263 requested changes

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/language/python/packaging/packaging.go
> +		content, err := ioutil.ReadAll(r)
https://go.dev/doc/go1.16#ioutil

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/language/python/packaging/packaging.go
> +		r = bytes.NewReader(pkginfoInZip)
analyzeEggZip should return io.Reader

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/language/analyze_test.go
> +				contentReader: bytes.NewReader([]byte("happy")),
We may want to use strings.NewReader

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/config/yaml/yaml.go
> +	content, err := ioutil.ReadAll(target.ContentReader)
https://go.dev/doc/go1.16#ioutil

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/config/hcl/hcl.go
> +	content, err := ioutil.ReadAll(target.ContentReader)
ditto

2021-11-29 05:56 UTC, knqyf263 commented on walker/tar.go
> +func (w *walker) fileWithTarOpener(fi os.FileInfo, r io.Reader) func() (io.ReadCloser, func() error, error) {
We can simply pass the file size instead of os.FileInfo.

2021-11-29 05:56 UTC, knqyf263 commented on walker/tar.go
> +				}
Any reason to create a temp directory?  Looks like `os.CreateTemp` is enough here.

2021-11-29 05:56 UTC, knqyf263 commented on walker/walk.go
> +const ThresholdSize = int64(200) << 20
```suggestion
const ThresholdSize = int64(200) << 20 // 200MB
```

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/analyzer.go
> +		}()
Seems like this defer will be called many times for the same file and it causes an error possibly. We have to be careful about when we call `cleaner()`.

2021-11-29 05:56 UTC, knqyf263 commented on analyzer/analyzer.go
> +	wg.Wait()
What made you add this here? It looks problematic.

2021-12-15 10:51 UTC, AkselAllas commented
This seems like an important improvement. Any timeline for this?

2021-12-23 16:54 UTC, knqyf263 approved these changes

2021-12-23 18:15 UTC, merged